services:
    BrightCloudStudio\RepFinderBundle\Controller\Backend\LocationsController:
        arguments:
            $db: '@doctrine.dbal.default_connection'
        public: true

    BrightCloudStudio\RepFinderBundle\Controller\FrontendModule\LocationsListController:
        tags:
            - { name: contao.frontend_module, type: locations_list, category: rep_finder }
